# Generated by Django 3.2 on 2021-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_processing_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
