# Generated by Django 3.2 on 2021-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_specialists_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='email',
            field=models.EmailField(default='arefyev.sergey@mail.ru', max_length=254, verbose_name='Почта'),
        ),
    ]
