# Generated by Django 3.2 on 2021-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/slider/', verbose_name='Картинка')),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
    ]
