# Generated by Django 3.2 on 2021-06-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
