# Generated by Django 3.2 on 2021-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequently_asked_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='relevance',
            field=models.IntegerField(default=1, help_text='Последовательность в каком порядке будут выводится на странице "F.A.Q"', verbose_name='Релевантность'),
            preserve_default=False,
        ),
    ]
