# Generated by Django 3.2 on 2021-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('post', models.CharField(max_length=256, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='img/employees/%Y/%m/%d', verbose_name='Фото')),
                ('relevance', models.IntegerField(help_text='Последовательность в каком порядке будут выводится на странице "Команда"', verbose_name='Релевантность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
